### PR TITLE
Update life.js to fix DNDBeyond Updates

### LINKED ISSUE #1: Script Breaks with DND Beyond Update + Multi-Classing
First problem: DND Beyond seems to have changed `characterClass` to `charClass`, which although a simple change seems to cause the script to break, changing this fixes it.

Second problem: My character is a cleric who just multi-classed into Monk, and the script does not work and the console shows that subclassDefinition is null. However, loading up a copy that has the monk class removed causes the script to work again.

I realize it's probably not your intention to keep working on this, as it really is a feature that should be implemented by the actual staff, but I would appreciate it if you could somehow manage to fix this. In the meanwhile, I suppose I'll just patch the subclass check out on my end.

### PR DESCRIPTION
**Pull request by SupremeDevice**
Fixes #1 
(Not the multi-classing bit but it does get it at least working a bit)

### CODE REVIEW

File: life.js [hunk 1]
```diff
@@ -1,9 +1,10 @@
 const lifeBeyond = async () => {
   const character = await fetchCharacter();
-  const lifeDomain = character.classes.filter((characterClass) => characterClass.subclassDefinition.name == 'Life Domain')[0];
+  const lifeDomain = character.classes.filter((charClass) => charClass.subclassDefinition.name == 'Life Domain')[0];
```
Comment (donoftime) [inline life.js]: In this case, `characterClass` is a variable name specified by us, rather than something that was specified by dndbeyond in their DOM. So this does not need to change.

For more information on this syntax, please see the [ES6 arrow function page on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) which I think gives a nice explanation.

File: life.js [hunk 2]
```diff
@@ -1,9 +1,10 @@
...
   if (lifeDomain == null) {
     return;  // nothing to do here
   }
+  await new Promise(resolve => setTimeout(resolve, 3000));
```
Comment (donoftime) [inline life.js]: Right here is where the core of the problem occurs. 

I looked into what is happening as the dndbeyond application initializes, and from what I see they are no longer loading the page all at once. Now, they are loading individual components one at a time -- I assume to improve the perceived page-load times. 

Before the update, our request for character data would have resolved long after the sidebar was on the screen. But now, after we get the character data from the backend, we try to begin observing the sidebar in the DOM only to find there is no sidebar on the screen!

The setTimeout here addresses that timing problem by providing a little 3 second pause before moving on to attach the spell book observer.

🤔 However, I generally try to avoid using time-based delays (aka "sleeps") as they are not always dependable. While the sidebar may be added to one person's screen after 2 seconds, for another person it may be 4 seconds and they would see the same problem again.

So instead of a time-based delay, I will put together a commit to add an event-based delay which watches the `document.body` for the sidebar to appear before attaching the spell book observer.

**Comment by donoftime** [comment]
I created a new character who is a Life Cleric with the Monk subclass to test, and with the changes above it seems to be working now 🙂 

I expect the issue you saw regarding subclassing was also related to the delays which occur while dndbeyond does its initial page load. 

I will go ahead and merge your PR and get it deployed to the chrome store
image
